server:
  port: 80
  servlet:
    context-path: /WF


spring:
  application:
    name: kflow_web
  datasource:
    url: jdbc:mysql://localhost:3306/ccflow9?serverTimezone=GMT%2B8
    username: root
    password: Kong123@
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:80/eureka/