server:
  port: 8081
  servlet:
    context-path: /WF


spring:
  application:
    name: kflow_web
  datasource:
    url: jdbc:mysql://localhost:3306/ccflow9?serverTimezone=GMT%2B8
    username: root
    password: Kong123@
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  mapperLocations: classpath:static/mapper/*.xml
  #配置对象别名，mapper中可以不指定包路径
  typeAliasesPackage: BP.springCloud.entity
#eureka配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://112.125.90.132:80/eureka/
      #defaultZone: http://127.0.0.1:80/eureka/


hanlp:
  termFile: /opt/es/elasticsearch-6.4.0/plugins/analysis-hanlp/data/dictionary/custom/my.txt
  #trainingFile: /opt/nlp/training/pku98/199801-train.txt
  #modelFile: /opt/nlp/model/cws.bin
  #testFile: /opt/nlp/training/pku98/199801-test.txt
  segmentTrainingFile: D:/Springboot/nlp/segment-mini.txt
  segmentModelFile: D:/Springboot/nlp/cws.bin
  word2vecModelFile: D:/Springboot/nlp/word2.txt
  word2vecTrainigFile: D:/Springboot/nlp/sogo_mini_word2.txt
  dir: D:/Springboot/nlp
  docFile: D:/Springboot/nlp/document.txt


